# -*- coding: utf-8 -*-
"""davron.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--yEab-UGsyDAalvlRosvlJTPUWV6gpG
"""

import matplotlib.pyplot as plt
import numpy as np

#x=np.array({3,5})
y=np.array([3,45])
plt.plot(y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

#x=np.array({3,10,5})
y=np.array([3,50,45])
plt.plot('x','y','o')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([5,3,7,9])
plt.plot(y,'o:r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([5,3,7,9])
plt.plot(y,marker='o',ms=20,mec="r")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3,4,])
y=np.array([0,2,4,6,8])
plt.xlabel("overs")
plt.ylabel("runs")
plt.title("sport data")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['cola','pepsi','fanta'])
y=np.array([12,15,18])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['cola','pepsi','fanta'])
y=np.array([12,15,18])

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,20])
mylabes=["cola","pepsi","fanta"]
myexplode=[0.2,0,0]
plt.pie(x,labels=mylabes)
plt.show()
#